### ISSUE TITLE
evil-mc broken in wdired mode?

### ISSUE THREAD

**Issue by rieje** [gabesoft/evil-mc#71]
In wdired mode, any attempts to create fake cursors creates them, but any movement to the original cursor does not move the fake cursors at all--they are stuck (the modeline says they are paused).

Also, on an unrelated note, there's no way to create fake cursors on all or only visually-selected lines, is there? You can specify `9999grj`, but that's not as good as say `VG` to select all lines then insert fake cursors that way.

**Comment by gabesoft** [comment]
I'll take a look when I have time. Did you try unpausing the cursors? The shortcut for that is grr. Regarding your note I wouldn't recommend creating too many cursors. Otherwise, operations will be really slow.  But I agree that being able to  create cursors on visually selected lines would be more convenient in some situations.

**Comment by rieje** [comment]
I revisited this and no longer have this issue but did have some weird behavior probably involving the read-only area in the left 2 columns wdired mode. At the moment normal usage seems to work and I can't consistent reproduce this issue so I'll close for now and re-open when I can find more info about it.
